### ISSUE TITLE
String of evil

### ISSUE THREAD

**Issue by JonasFhInfo** [JonasFhInfo/SE01_UML_Ersteller#4]
{interface Duck; private flyBehavior Flyable, private quackBehavior Quackable; public display() void, public fly() void, public quack (int i, char character) int; knows Door, is only part of Door, implements Duck}, {interface Buck;;;}

**Comment by JonasFhInfo** [comment]
Sobald es mehr als eine Klasse und eine davon ne Bezeihung hat, panicked es.

thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', C:\projects\rust\src\libcore\slice\mod.rs:2085:10

**Comment by juwr** [comment]
Sollte gefixt sein.
